const gaming = [
  {
    ref: "gaming_1",
    category: "gaming",
    name: "FIFA 23",
    price: 50,
    unit: "piece",
    image: "./assets/gaming/1.jpg",
  },
  {
    ref: "gaming_2",
    category: "gaming",
    name: "SEKIRO",
    price: 40,
    unit: "piece",
    image: "./assets/gaming/2.jpg",
  },
  {
    ref: "gaming_3",
    category: "gaming",
    name: "Farcry 6",
    price: 30,
    unit: "piece",
    image: "./assets/gaming/farcry6.jpg",
  },
  {
    ref: "gaming_4",
    category: "gaming",
    name: "G O W",
    price: 20,
    unit: "piece",
    image: "./assets/gaming/gof of war.jpg",
  },
  {
    ref: "gaming_5",
    category: "gaming",
    name: "NBA 2K23",
    price: 10,
    unit: "piece",
    image: "./assets/gaming/nba23.jpg",
  },
  {
    ref: "gaming_6",
    category: "gaming",
    name: "Naruto 4",
    price: 5,
    unit: "piece",
    image: "./assets/gaming/naruto4.jpg",
  },

  {
    ref: "gaming_7",
    category: "gaming",
    name: "tourismo",
    price: 50,
    unit: "piece",
    image: "./assets/gaming/grand tourismo.jpg",
  },
  {
    ref: "gaming_8",
    category: "gaming",
    name: "GTA5",
    price: 40,
    unit: "piece",
    image: "./assets/gaming/GTA5.jpg",
  },
  {
    ref: "gaming_9",
    category: "gaming",
    name: "mortal",
    price: 30,
    unit: "piece",
    image: "./assets/gaming/Mortal.jpg",
  },
  {
    ref: "gaming_10",
    category: "gaming",
    name: "VALHALLA",
    price: 20,
    unit: "piece",
    image: "./assets/gaming/AC valhalla.jpg",
  },
  {
    ref: "gaming_11",
    category: "gaming",
    name: "Rocket",
    price: 10,
    unit: "piece",
    image: "./assets/gaming/Rocket.jpg",
  },
  {
    ref: "gaming_12",
    category: "gaming",
    name: "Rocket",
    price: 5,
    unit: "piece",
    image: "./assets/gaming/Rocket.jpg",
  },
  {
    ref: "gaming_13",
    category: "gaming",
    name: "the last",
    price: 50,
    unit: "piece",
    image: "./assets/gaming/the last.jpg",
  },
  {
    ref: "gaming_14",
    category: "gaming",
    name: "UFC4",
    price: 40,
    unit: "piece",
    image: "./assets/gaming/UFC4.jpg",
  },
  {
    ref: "gaming_15",
    category: "gaming",
    name: "vangard",
    price: 30,
    unit: "piece",
    image: "./assets/gaming/vangard.jpg",
  },
];

const accessoires = [
  {
    ref: "accessoires_1",
    category: "accessoires",
    name: "Casque",
    price: 50,
    unit: "piece",
    image: "./assets/accessoires/casque.jpg",
  },
  {
    ref: "accessoires_2",
    category: "accessoires",
    name: "Manette",
    price: 40,
    unit: "piece",
    image: "./assets/accessoires/manette.jpg",
  },
  {
    ref: "accessoires_3",
    category: "accessoires",
    name: "Souris",
    price: 30,
    unit: "piece",
    image: "./assets/accessoires/souris.jpg",
  },
  {
    ref: "accessoires_4",
    category: "accessoires",
    name: "Clavier",
    price: 20,
    unit: "piece",
    image: "./assets/accessoires/clavier.jpg",
  },
  {
    ref: "accessoires_5",
    category: "accessoires",
    name: "Tapis de souris",
    price: 10,
    unit: "piece",
    image: "./assets/accessoires/tapis de souris.jpg",
  },
  {
    ref: "accessoires_6",
    category: "accessoires",
    name: "Casque",
    price: 5,
    unit: "piece",
    image: "./assets/accessoires/casque2jpg.jpg",
  },
];

const chaussures =[
    {
        ref: "chaussures_1",
        category: "chaussures",
        name: "Adidas",
        price: 50,
        unit:"piece",
        image: "./assets/chaussures/adidas.jpg",
    },
    {
        ref: "chaussures_2",
        category: "chaussures",
        name: "Nike",
        price: 40,
        unit:"piece",
        image: "./assets/chaussures/nike.jpg",
    },
    {
        ref: "chaussures_3",
        category: "chaussures",
        name: "Puma",
        price: 30,
        unit:"piece",
        image: "./assets/chaussures/pumajpg.jpg",
    },
  
]

const maillot =[
    {
        ref: "maillot_1",
        category: "maillot",
        name: "Tennis",
        price: 50,
        unit:"piece",
        image: "./assets/maillot/tenis.jpg",
    },
    {
        ref: "maillot_2",
        category: "maillot",
        name: "Basketball",
        price: 40,
        unit:"piece",
        image: "./assets/maillot/nba.jpg",
    },
    {
        ref: "maillot_3",
        category: "maillot",
        name: "Football",
        price: 30,
        unit:"piece",
        image: "./assets/maillot/football.jpg",
    },
    
]

export const list = [gaming, accessoires, chaussures, maillot]

